permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
markdown: kramdown

title : Untitled
author : "Untitled"
name : "Into The Void"
email : intothevoid1631@gmail.com
github : intothevoid1631
twitter :
feedburner :

production_url : http://intothevoid1631.github.io
